image: Visual Studio 2017

version: '1.0.{build}'
max_jobs: 1

before_build:
- nuget restore BASRemote.NET.sln
build:
  project: BASRemote.NET.sln
  publish_nuget: true
  verbosity: minimal
after_build:
  - cmd: cd BASRemote.Tests
  - cmd: dotnet test
deploy:
  - provider: NuGet
    api_key:
      secure: 0kI/E6vKNAtR5RcHodtKMAI/7zxURJxUznyo1Su+UiCkiaD5d/BfE8PxCxvjtu0p
    on:
      branch: master

